Repository OlympusDAO/olympus-frontend, pull requests merged in 2022-01, with the labels that each got.

#1062 update ohm marketPrice & bond price in bonds-v2
  src/slices/BondSliceV2.ts
  src/views/BondV2/BondV2.tsx
Labels: bonds-v2

#1067 set up codeql workflow
  .github/workflows/codeql.yml
  src/helpers/QueryParameterHelper.ts
Labels: enhancement, security

#1083 Adjust ImpactMarket's give goal per request
  src/views/Give/projects.json
Labels: give

#1024 DataRow to component-library
  package.json
  src/views/33Together/PoolDeposit.jsx
  src/views/33Together/PoolInfo.jsx
  src/views/Bond/BondPurchase.jsx
  src/views/Bond/BondRedeem.jsx
  src/views/Give/RedeemYield.tsx
  src/views/Stake/Stake.tsx
  src/views/Stake/StakeRow.tsx
  src/views/V1-Stake/V1-Stake.jsx
  src/views/Wrap/Wrap.jsx
  src/views/Wrap/WrapCrossChain.tsx
  yarn.lock
Labels: component-library

#1034 metric component to component-library
  src/components/Metric/Metric.scss
  src/components/Metric/Metric.tsx
  src/components/Metric/MetricCollection.tsx
  src/components/Metric/index.tsx
  src/views/ChooseBond/ChooseBond.tsx
  src/views/Stake/Stake.tsx
  src/views/TreasuryDashboard/TreasuryDashboard.tsx
  src/views/TreasuryDashboard/components/Metric/Metric.js
  src/views/V1-Stake/V1-Stake.jsx
  src/views/Wrap/Wrap.jsx
Labels: component-library

#1145 moving give assets to component-library. removing unused assets from repo.
  package.json
  src/assets/icons/arrow-right.svg
  src/assets/icons/check-circle.svg
  src/assets/icons/clock.svg
  src/assets/icons/donated.svg
  src/assets/icons/donors.svg
  src/assets/icons/goal.svg
  src/assets/icons/vault-lock.svg
  src/assets/icons/website.svg
  src/assets/icons/yield.svg
  src/components/EducationCard.tsx
  src/components/GiveProject/ProjectCard.tsx
  yarn.lock
Labels: component-library

#1170 Social footer
  src/components/Sidebar/Social.jsx
  src/components/Sidebar/Social.tsx
Labels: component-library

#1124 Feature/bonds modal
  src/views/Bond/BondHeader.tsx
  src/views/Bond/bondSettings.scss
  src/views/BondV2/AdvancedSettings.jsx
  src/views/BondV2/BondHeader.jsx
  src/views/BondV2/bondSettings.scss
Labels: component-library

#1204 Migration modal single
  src/components/Migration/MigrationModalSingle.tsx
Labels: component-library

#1180 moving sidebar nav items to component library.
  src/assets/icons/33-together.svg
  src/assets/icons/bond.svg
  src/assets/icons/bridge.svg
  src/assets/icons/dashboard.svg
  src/assets/icons/give.svg
  src/assets/icons/new-icon.svg
  src/assets/icons/wrap.svg
  src/components/Sidebar/NavContent.jsx
  src/components/Sidebar/externalUrls.jsx
  src/components/Sidebar/sidebar.scss
Labels: component-library

#1119 Feature/expanded chart modal
  src/components/Chart/ExpandedChart.jsx
Labels: component-library

#1165 removing unused svgs. moving wallet svgs to component-library
  src/assets/icons/more.svg
  src/assets/tokens/gohm.png
  src/components/TopBar/Wallet/InitialWalletView.tsx
  src/components/TopBar/Wallet/Token.tsx
Labels: component-library

#1222 Dashboard Component Library Conversion
  src/components/Chart/ExpandedChart.jsx
  src/views/TreasuryDashboard/TreasuryDashboard.tsx
  src/views/TreasuryDashboard/components/Graph/Graph.js
  src/views/TreasuryDashboard/components/Metric/Metric.js
  src/views/TreasuryDashboard/treasuryData.ts
Labels: component-library

#1251 Bond SVGs into Component Library / TokenStack Component
  package.json
  src/assets/tokens/CVX.svg
  src/assets/tokens/DAI.svg
  src/assets/tokens/FRAX.svg
  src/assets/tokens/LUSD.svg
  src/assets/tokens/OHM-DAI.svg
  src/assets/tokens/OHM-FRAX.svg
  src/assets/tokens/OHM-LUSD.svg
  src/assets/tokens/OHM-WETH.svg
  src/assets/tokens/UST.svg
  src/assets/tokens/wBTC.svg
  src/components/BondLogo.jsx
  src/constants.ts
  src/helpers/AllBonds.ts
  src/lib/Bond.ts
  src/locales/index.ts
  src/slices/AccountSlice.ts
  src/slices/BondSliceV2.ts
  src/views/Bond/BondHeader.tsx
  src/views/BondV2/BondHeader.jsx
  src/views/BondV2/BondRow.tsx
  src/views/BondV2/ClaimRow.tsx
  src/views/BondV2/choosebond.scss
  src/views/ChooseBond/BondRow.tsx
  src/views/ChooseBond/ClaimRow.tsx
  yarn.lock
Labels: component-library

#1300 Fixes claiming of expired bonds
  src/slices/BondSliceV2.ts
Labels: bug, sev1

#1285 updating readme with component-library info
  README.md
Labels: component-library

#1288 Stake Views Paper Component
  src/views/Stake/ExternalStakePool.tsx
  src/views/Stake/Stake.tsx
  src/views/Stake/__tests__/__snapshots__/Stake.unit.test.tsx.snap
  src/views/V1-Stake/V1-Stake.jsx
Labels: component-library

#1312 Bond V1 & V2 Modal using Component-Library Modal
  src/views/Bond/Bond.tsx
  src/views/Bond/BondHeader.tsx
  src/views/Bond/BondPurchase.tsx
  src/views/Bond/BondRedeem.tsx
  src/views/Bond/bond.scss
  src/views/BondV2/BondHeader.jsx
  src/views/BondV2/BondPurchase.tsx
  src/views/BondV2/BondV2.tsx
  src/views/BondV2/bond.scss
Labels: component-library

#1341 Fix mis-spelling in give project
  public/assets/images/give/kolektivo/kolektivo-logo.png
  public/assets/images/give/kolektivo/kolektivo-logo.svg
  src/views/Give/projects.json
Labels: give

#1290 Moving Bond views to component-library paper
  src/views/BondV2/ChooseBondV2.tsx
  src/views/BondV2/ClaimBonds.tsx
  src/views/BondV2/ClaimRow.tsx
  src/views/BondV2/choosebond.scss
  src/views/ChooseBond/ChooseBond.tsx
  src/views/ChooseBond/ClaimBonds.tsx
  src/views/ChooseBond/ClaimRow.tsx
Labels: component-library

#1352 v2 bond input to component library input
  src/views/BondV2/BondPurchase.tsx
Labels: component-library

#1349 Stake Input to Component Library
  package.json
  src/views/Stake/Stake.tsx
  yarn.lock
Labels: component-library

#1350 removing unused svgs
  src/assets/icons/Immunefi.svg
  src/assets/icons/caret-down.svg
  src/assets/icons/circle-more.svg
  src/assets/icons/circle-zap.svg
  src/assets/icons/discord.svg
  src/assets/icons/docs.svg
  src/assets/icons/feedback.svg
  src/assets/icons/forum.svg
  src/assets/icons/github.svg
  src/assets/icons/governance.svg
  src/assets/icons/info-fill.svg
  src/assets/icons/info.svg
  src/assets/icons/lock.svg
  src/assets/icons/medium.svg
  src/assets/icons/moon.svg
  src/assets/icons/settings.svg
  src/assets/icons/stake.svg
  src/assets/icons/sun.svg
  src/assets/icons/twitter.svg
  src/assets/icons/zap.svg
  src/assets/tokens/token_wsOHM.svg
Labels: component-library

#1368 ExternalStakePool Mobile DataRow
  package.json
  src/views/Stake/ExternalStakePool.tsx
  yarn.lock
Labels: component-library
