Repository OlympusDAO/olympus-frontend, pull requests merged in 2022-02, with the labels that each got.

#1389 moving 33Together Inputs to component-library input wrapper
  src/views/33Together/PoolDeposit.tsx
  src/views/33Together/PoolWithdraw.tsx
Labels: component-library

#1387 33together confirmation modal to component library
  src/assets/tokens/token_33T.svg
  src/views/33Together/ConfirmationModal.tsx
Labels: component-library

#1388 chore: jest update
  README.md
  package.json
  yarn.lock
Labels: dependencies, test suite

#1386 WrapCrossChain . Paper to Component Library. Metric Component Refactor
  src/views/Wrap/WrapCrossChain.tsx
  src/views/Wrap/__tests__/__snapshots__/WrapCrossChain.unit.test.tsx.snap
Labels: component-library

#1382 wrap input to component-library input
  src/views/Wrap/Wrap.tsx
  src/views/Wrap/WrapCrossChain.tsx
Labels: component-library

#1384 moving zap to component library paper
  src/views/Zap/Zap.tsx
  src/views/Zap/ZapStakeAction.tsx
  src/views/Zap/__tests__/__snapshots__/Zap.unit.test.tsx.snap
Labels: component-library

#1383 33Together Paper to Component Library
  src/components/CardHeader/CardHeader.scss
  src/components/CardHeader/CardHeader.tsx
  src/components/CardHeader/__tests__/CardHeader.unit.test.tsx
  src/components/CardHeader/__tests__/__snapshots__/CardHeader.unit.test.tsx.snap
  src/components/CardHeader/cardheader.scss
  src/views/33Together/33together.tsx
  src/views/33Together/PoolInfo.tsx
  src/views/33Together/__tests__/__snapshots__/33Together.unit.test.tsx.snap
Labels: component-library

#1143 Move everything to existing ConnectButton Component. Add component-library to connectbutton
  src/__tests__/__snapshots__/Root.unit.test.tsx.snap
  src/components/ConnectButton/ConnectButton.tsx
  src/components/ConnectButton/__tests__/__snapshots__/ConnectButton.unit.test.tsx.snap
  src/views/33Together/__tests__/__snapshots__/33Together.unit.test.tsx.snap
  src/views/Give/Give.tsx
  src/views/Give/RecipientModal.tsx
  src/views/Give/__tests__/__snapshots__/Give.unit.test.tsx.snap
  src/views/Stake/Stake.tsx
  src/views/Stake/__tests__/__snapshots__/Stake.unit.test.tsx.snap
  src/views/V1-Stake/V1-Stake.jsx
  src/views/Wrap/Wrap.tsx
  src/views/Wrap/WrapCrossChain.tsx
  src/views/Wrap/__tests__/__snapshots__/Wrap.unit.test.tsx.snap
  src/views/Wrap/__tests__/__snapshots__/WrapCrossChain.unit.test.tsx.snap
  src/views/Zap/__tests__/__snapshots__/Zap.unit.test.tsx.snap
Labels: component-library

#1484 Fix jest run not completing in CI
  .github/workflows/main.yml
  package.json
Labels: test suite, continuous-integration

#1446 Migrate Give to use the component library
  package.json
  src/components/EducationCard.tsx
  src/components/GiveProject/ProjectCard.tsx
  src/components/__tests__/__snapshots__/EducationCard.unit.test.tsx.snap
  src/views/BondV2/Bond.scss
  src/views/Give/CausesDashboard.tsx
  src/views/Give/DepositRow.tsx
  src/views/Give/Give.scss
  src/views/Give/Give.tsx
  src/views/Give/GiveInfo.tsx
  src/views/Give/ManageDonationModal.tsx
  src/views/Give/RecipientModal.tsx
  src/views/Give/RedeemYield.tsx
  src/views/Give/RedeemYieldModal.tsx
  src/views/Give/WithdrawDepositModal.tsx
  src/views/Give/YieldRecipients.tsx
  src/views/Give/__tests__/__snapshots__/Give.unit.test.tsx.snap
  yarn.lock
Labels: component-library, give

#1522 Force upgrade of indirect dependencies to address vulnerabilities
  package.json
  yarn.lock
Labels: dependencies, security
